# ./docker-compose.yaml

# DEV docker compose file ——————————————————————————————————————————————————————
# Check out: https://docs.docker.com/compose/gettingstarted/
version: '3.7'

# docker-compose -f docker-compose.yaml up -d
services:

    # Database ———————————————————————————————————————————————————————————————————

    # MySQL server database (official image)
    # https://docs.docker.com/samples/library/mysql/
    db:
        image: mysql:5.7
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root

    # adminer database interface (official image)
    # https://hub.docker.com/_/adminer
    adminer:
        container_name: adminer
        depends_on:
            - db
        image: adminer
        ports:
            - "8089:8080"

    # elasticsearch ——————————————————————————————————————————————————————————————

    # elasticsearch server (official image)
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3 # 6.8.4 out
        ports:
            - "9209:9200"
        environment:
            - "discovery.type=single-node"
            - "bootstrap.memory_lock=true"
            - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
            - "xpack.security.enabled=false"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=*"

    # elasticsearch head manager (fork of mobz/elasticsearch-head for elasticsearch 6)
    # /!\ it isn't an official image /!\
    # https://hub.docker.com/r/tobias74/elasticsearch-head
#    elasticsearch-head:
#        container_name: sb-elasticsearch-head
#        depends_on:
#            - elasticsearch
#        image: tobias74/elasticsearch-head:6
#        ports:
#            - "9109:9100"

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:6.8.18
        ports:
            - "5601:5601"
        environment:
            - "ELASTICSEARCH_URL=http://elasticsearch"
        depends_on:
            - elasticsearch

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.7-management
        ports:
            - "5673:5672"
            - "15673:15672"
    n8n:
        image: n8nio/n8n
        ports:
            - "5678:5678"

    redis:
        container_name: redis
        image: redis:5-alpine
        ports: [6379]

    imaginary:
        image: h2non/imaginary:latest
        # optionally mount a volume as local image source
        volumes:
            - ./images:/mnt/data
        environment:
            PORT: 9000
        command: -enable-url-source -mount /mnt/data
        ports:
            - "9001:9000"

    mailer:
        image: maildev/maildev
        ports:
            - "1180:80"

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: access1234
            MINIO_ROOT_PASSWORD: secret1234
        volumes:
            -   ./data/minio:/data
        command: server /data --console-address ":9002"
        ports:
            - "9090:9000"
            - "9002:9002"
